#!/usr/bin/env bash

# build configuration file, see README for the variables it should define
if [ -e ".build-config" ]; then
   source ".build-config"
fi

#buildah pull "${REGISTRY_DOMAIN}/texstyle-container"
#buildah pull "${REGISTRY_DOMAIN}/test-container"
#buildah pull "${REGISTRY_DOMAIN}/packaging-container"